Importing command from text
iis-powp-2022/powp_jobs2d_projects pull request #13
Opened 2022-04-20 09:16 UTC by piterm11

2022-04-20 09:34 UTC, kowallus requested changes
Follow suggestions please.

2022-04-20 09:34 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/file/IImportCommand.java
> +	List<DriverCommand> importCommandSequence(String filename);
importing should be done from a text, not from a file. Reading text from a file is a separate task (responsibility)

2022-04-20 09:34 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +import edu.kis.powp.jobs2d.command.file.ImportXMLFileCommand;
Try to remove these dependencies. An appropriate importer could be supplied from an external facility (e.g., kind of a factory).

2022-04-20 09:34 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +import edu.kis.powp.jobs2d.command.ComplexCommand;
Is it used?!

2022-05-03 18:45 UTC, piterm11 commented
Fixed

2022-05-04 07:06 UTC, kowallus requested changes
Please apply minor cleanup

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/file/ImportCMDFileCommand.java
>  import java.io.FileReader;
Remove unused imports

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/file/IImportCommand.java
>  	List<DriverCommand> importCommandSequence(String filename);
Please update the name of the param

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/file/ImportJSONFileCommand.java
> -		} catch (IOException e) {
Cleanup imports

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/file/ImportXMLFileCommand.java
> +		processText(filename);
Only a comment: this private method seems unnecessary.

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/file/ImporterFactory.java
> +				throw new IllegalArgumentException();
Is this handled gracefully?

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +		List<DriverCommand> commandList = importCommand.importCommandSequence(text);
Only checking: how do you handle invalid input?

2022-05-04 07:06 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +import edu.kis.powp.jobs2d.command.file.*;
why *? How many imports from file package you use?

2022-05-04 08:40 UTC, pioter00 commented
fixed

2022-05-04 08:42 UTC, merged