deep copy of ComplexCommand
iis-powp-2022/powp_jobs2d_projects pull request #16
Opened 2022-04-26 17:10 UTC by bartekmaka06

2022-04-27 13:28 UTC, kowallus requested changes
The solution looks fine. There is one issue which requires your attention.

2022-04-27 13:38 UTC, bartekmaka06 commented
Is it copy method in DriverCommandManager class?

2022-04-28 09:15 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/manager/DriverCommandManager.java
> +
You shouldn't simply add code not working correctly. Maybe e.g., it is possible to replace anonymous ICompoundCommand() with ComplexCommand implementation.

2022-04-28 09:15 UTC, kowallus commented
Yes. I added a missing comment (I think I forgot to confirm it)

2022-05-04 06:38 UTC, kowallus requested changes
Please be more careful

2022-05-04 06:38 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/ComplexCommand.java
> +    String name=null;
should be private!
I suggest avoiding this null value. Is public ComplexCommand(List<DriverCommand> commandList) constructor necessary?

2022-05-11 08:28 UTC, kowallus approved these changes

2022-05-11 08:28 UTC, merged