Monitor feature implemented using decorator design pattern
iis-powp-2022/powp_jobs2d_projects pull request #20
Opened 2022-05-04 21:08 UTC by FawBiotechnologist

This is our first proposition, let us know if that's what you were asking for.

2022-05-12 13:29 UTC, kowallus requested changes
Some minor issues.

2022-05-12 13:29 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/decorators/Job2dDriverMonitorDecorator.java
> +	// ze wzoru na odleglosc miedzy dwoma punktami
komentarz zbędny

2022-05-12 13:29 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/decorators/Job2dDriverMonitorDecorator.java
> +	private double operationalDistanceTraveled;
Add getters to make the usage monitor potentially usable.

2022-05-12 13:29 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/drivers/decorators/Job2dDriverMonitorDecorator.java
> +public final class Job2dDriverMonitorDecorator extends BaseJob2dDriverDecorator {
I suggest Job2dDriverUsageMonitorDecorator

2022-05-16 10:20 UTC, FawBiotechnologist commented
I fixed all mentioned issues in separate commits. Re-review, and let us know if there are still any issues to fix.

2022-05-16 19:13 UTC, merged