Visitor canvas
iis-powp-2022/powp_jobs2d_projects pull request #31
Opened 2022-05-25 08:59 UTC by JakZaj

2022-05-25 09:13 UTC, kowallus requested changes
small refactor suggestions

2022-05-25 09:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/visitor/canvas/Canvas.java
> +
This is a RectangularCanvas. Please extract also a sole interface to enable support of wider range of canvases.

2022-05-25 09:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/visitor/canvas/A4Canvas.java
> +	public A4Canvas() {
A4Canvas looks like a specific version of CustomCanvas (superclass?)

2022-05-25 09:13 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/visitor/canvas/IsInBoundsVisitor.java
> +		}
This approach is not reusable (visitor can be called once). If this method kept local isInBounds varialble the other visit methods could be simpler:
isInBounds = canvas.isInBounds(setPositionCommand.getPosX(),setPositionCommand.getPosY());

2022-05-25 11:16 UTC, 209424 approved these changes

2022-05-30 11:50 UTC, kowallus approved these changes
Nice :)

2022-05-30 11:51 UTC, merged