Feature preview
iis-powp-2022/powp_jobs2d_projects pull request #35
Opened 2022-06-01 08:38 UTC by piterm11

2022-06-01 08:43 UTC, kowallus requested changes
I cannot see much improvement

2022-06-01 08:43 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerPreview.java
> +	LineDriverAdapter lineAdapter;
private!

2022-06-01 08:43 UTC, kowallus commented on src/main/java/edu/kis/powp/jobs2d/command/gui/CommandManagerWindow.java
> +		preview = new CommandManagerPreview(previewPanel, new BasicLine());
dependencies from CommandManagerPreview burden CommandManagerWindow. You didn't manage to inverse dependencies.

2022-06-01 08:48 UTC, piterm11 commented
Changes have been made

2022-06-01 09:38 UTC, pioter00 commented
I hope it is finally done.

2022-06-02 20:11 UTC, kowallus approved these changes
Great! 5 pts final

2022-06-02 20:12 UTC, merged