convert mouse clicks to driver calls
iis-powp-2022/powp_jobs2d_projects pull request #7
Opened 2022-04-12 21:35 UTC by zgontea

Jan Gontarek 228737
Franciszek Karwowski 228765

2022-04-12 21:51 UTC, kowallus requested changes
Please clean the code.

2022-04-12 21:51 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +				int correctedY = e.getY() - 227;
How did you get those values? 
They are not arbitrary constants so they should be calculated

2022-04-12 21:51 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +		application.getFreePanel().addMouseListener(new MouseInputAdapter() {
Please extract this adapter to a separate file.

2022-04-12 21:51 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +				DriverFeature.getDriverManager().getCurrentDriver().operateTo(correctedX, correctedY);
It would be nice to provide a way to use setPosition (maybe right-click?)

2022-04-13 08:42 UTC, zgontea commented
Requested changes applied 🗻

2022-04-13 08:54 UTC, kowallus requested changes
One more time

2022-04-13 08:54 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/MouseListener.java
> +                DriverFeature.getDriverManager().getCurrentDriver().setPosition(correctedX, correctedY);
Duplicated code: DriverFeature.getDriverManager().getCurrentDriver()

2022-04-13 08:54 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/events/MouseListener.java
> +                DriverFeature.getDriverManager().getCurrentDriver().operateTo(correctedX, correctedY);
Try remove coupling with DriverFeature.

2022-04-13 08:54 UTC, kowallus commented on src/test/java/edu/kis/powp/jobs2d/TestJobs2dApp.java
> +		application.getFreePanel().addMouseListener(new MouseListener(application.getFreePanel()));
amazing!!! Please make it simpler. Try to remove application.getFreePanel() code duplication.

2022-04-13 09:21 UTC, kowallus approved these changes

2022-04-13 09:21 UTC, merged

2022-05-04 08:28 UTC, kowallus commented
Unfortunately, PR went to the wrong branch!